### ISSUE TITLE
.parquet vides ou weather dans le bucket GCP des station-status

### ISSUE THREAD

**Issue by AntoineGiraud** [MaxHalford/bike-sharing-history#2]
Il y a, dans le bucket (bike-sharing-history)[https://console.cloud.google.com/storage/browser/bike-sharing-history] 58 `.parquet` vides & des fichiers `./weather/` empêchant de pouvoir charger TOUTES les villes dans DuckDB

```sql
SET s3_endpoint='storage.googleapis.com';
select * from READ_PARQUET('s3://bike-sharing-history/**/*.parquet', filename = true)
```

ex : `bordeaux/vcub/2024/Jan.parquet`, `vannes/veloceo/2024/Jan.parquet`

requête pour en avoir le cœur net :

```sql
select *
from parquet_metadata('s3://bike-sharing-history/**/*.parquet')
where column_id = 0 and (path_in_schema != 'station' or num_values <= 1);
```

**Comment by MaxHalford** [comment]
All good now!
