### ISSUE TITLE
Défi dockless & doublons nom station

### ISSUE THREAD

**Issue by AntoineGiraud** [MaxHalford/bike-sharing-history#4]
On peut avoir des doublons de nom de station dans les dockless (ex: `6 All. de Tourny, 33000 Bordeaux, France`)
- car pas la mm station_area
- attention aux pk de station !

3 millions de lignes avec doublon
```sql
select station, filename, commit_at, count(1) nb
from raw.raw_station_status
where filename like '%bordeaux%'
group by all having nb>1;
```

**Comment by MaxHalford** [comment]
J'ai enlevé Bordeaux et toutes les autres stations dockless, c'est plus simple pour le moment.
